import { Inter } from 'next/font/google'
import './globals.css'

const inter = Inter({ subsets: ['latin'] })

// component
import Header from '@/components/header'
// import Footer from '@/components/footer'

//Theme Provider
import { ThemeProvider } from '@/components/ThemeProvider'

export const metadata = {
  title: 'Project Base Learning',
  description: 'Generated by create next app',
}

export default function RootLayout({ children }) {
  return (
    <html lang="en" suppressContentEditableWarning>
      <body className={inter.className}>
        <ThemeProvider attribute='class' defaultThemes='light'>
        <Header/>
        {children}
        {/* <Footer/> */}
        </ThemeProvider>
      </body>
    </html>
  )
}
